# Replace the text below to customize your site
site_name: Mariana Ponde Dhelomme - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Mariana Ponde Dhelomme
copyright: Copyleft 2021 "Mariana Ponde Dhelomme" - GNU Free Documentation License
repo_name: 'Name : Github Repo'
site_url: https://fablabbcn.github.io/mdef-template/
repo_url: 'https://github.com/fablabbcn/mdef-template'


nav:
  - Home: index.md
  - About: about/me.md
  - Design Dialogues: DesignDialogues/DD.md
  - Master project:
      - Initial ideas: project/project.md
      - Communication Strategies: project/Strategies.md
      - Reflection Term 1: project/Strategies.md
  - Reflections :
      - Term 1:
        - Bootcamp: term1/01-Bootcamp.md
        - AoWS: term1/02-Atlas of Weak Signals.md
        - Prototyping: term1/03-Prototyping.md
        - Bio & Agri Zero: term1/04-BioAgriZero.md
        - Living w/ Your Own Ideas: term1/05-LivingWithIdeas.md
        - Tech Beyond The Myth: term1/06-TechBeyondMyth.md
        - Community Engagement: term1/07-CommunityEngagement.md
        - Extended Intelligences: term1/08-ExtendedIntelligences.md
      - Term 2:
        - Design Studio: term2/15-DesignStudioT2.md
        - Designing for the Next Billion Seconds: term2/09-DesigningNextBillion.md
        - Remixing Materials: term2/10-RemixingMaterials.md
        - Making Sense and Meaning: term2/11-MakingSenseAndMeaning.md
        - Prototyping for Design: term2/12-PrototypingForDesign.md
        - Communicating Ideas: term2/13-CommunicatingIdeas.md
        - Measuring the World: term2/14-MeasuringTheWorld.md
        - Future Talks: term2/16-FutureTalks.md
      - Term 3:
        - Design Studio 3: term3/20-DesignStudio3.md
        - El Hierro: term3/23-ElHierro.md
        - Distributed Design: term3/17-DistributedDesign.md
        - Prototyping for Design 2.0: term3/18-Prototyping2.md
        - Design Ethics: term3/19-DesignEthics.md
        - DAOs: term3/21-DAO.md
        - MicroChallenge III: term3/22-MicroChallengeIII.md

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: black
    accent: red
  font:
    # See available fonts at https://fonts.google.com/
    text: Roboto Mono
    code: Cutive Mono
  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
